name: testBuildDeployToCF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.11

    - name: Test
      run: go test -v ./...
      
  deploy:
    runs-on: ubuntu-20.04
    needs: [test]

    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy app
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: https://api.cf.dev.datev.cloud
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: helloworld
          cf_space: github
          command: push -f manifest.yml
